CREATE TABLE stops (
  id integer primary key, 
  name string,
  section string,
  remote_id integer
);

INSERT INTO stops (name, section, remote_id) VALUES ('1 Av & Blanchard St', '1', 121);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av & Marion St', '1', 108);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av & Union St', '1', 114);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av & University St', '1', 113);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av & Virginia St', '1', 119);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av & Warren Pl', '1', 3547);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av N & Denny Wy', '1', 4304);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av N & Republican St', '1', 4324);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av N & Thomas St', '1', 4367);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av S & S Atlantic St', '1', 1640);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av S & S Jackson St', '1', 101);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av S & S Royal Brougham Wy', '1', 4017);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av S & S Spokane St (E/N)', '1', 4006);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av S & S Spokane St (W/S)', '1', 4051);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av W & W Mercer St', '1', 4365);
INSERT INTO stops (name, section, remote_id) VALUES ('1 Av W & W Raye St', '1', 4314);
INSERT INTO stops (name, section, remote_id) VALUES ('10 Av E & E Aloha St', '1', 1601);
INSERT INTO stops (name, section, remote_id) VALUES ('10 Av E & E Mercer St', '1', 1667);
INSERT INTO stops (name, section, remote_id) VALUES ('10 Av W & W Fulton St', '1', 4311);
INSERT INTO stops (name, section, remote_id) VALUES ('11 Av NE & NE 45 St', '1', 5928);
INSERT INTO stops (name, section, remote_id) VALUES ('11 Av NE & NE 47 St', '1', 5667);
INSERT INTO stops (name, section, remote_id) VALUES ('12 Av NE & NE 47 St', '1', 5533);
INSERT INTO stops (name, section, remote_id) VALUES ('12 Av NE & NE 75 St', '1', 5523);
INSERT INTO stops (name, section, remote_id) VALUES ('12 Av NE & NE Campus Pkwy (W/B)', '1', 5953);
INSERT INTO stops (name, section, remote_id) VALUES ('12 Av S & S Jackson St', '1', 2108);
INSERT INTO stops (name, section, remote_id) VALUES ('14 Av & E Jefferson St', '1', 2119);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av & E Madison St', '1', 2106);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av E & E Galer St', '1', 1680);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av E & E John St', '1', 1643);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av NE & NE 42 St', '1', 5909);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av NE & NE 43 St', '1', 5917);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av NE & NE 45 St', '1', 5912);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av NE & NE 50 St', '1', 5540);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av NE & NE 65 St', '1', 5506);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av NE & NE 75 St', '1', 5559);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av NE & NE Campus Pkwy', '1', 5905);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av NW & NW 64 St', '1', 3041);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av NW & NW Leary Wy (N/B)', '1', 3024);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av NW & NW Leary Wy (S/B)', '1', 3026);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av NW & NW Market St', '1', 3004);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av S & Beacon Av S', '1', 2506);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av S & S Columbian Wy', '1', 2633);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av W & W Dravus St', '1', 3504);
INSERT INTO stops (name, section, remote_id) VALUES ('15 Av W & W Garfield St', '1', 3502);
INSERT INTO stops (name, section, remote_id) VALUES ('15th Av NW & NW Leary Wy', '1', 10017);
INSERT INTO stops (name, section, remote_id) VALUES ('16 Av E & E Denny Wy', '1', 1674);
INSERT INTO stops (name, section, remote_id) VALUES ('16 Av SW & SW Florida St', '1', 6015);
INSERT INTO stops (name, section, remote_id) VALUES ('17 Av & E Jefferson St', '1', 2150);
INSERT INTO stops (name, section, remote_id) VALUES ('17 Av NW & NW Market St', '1', 3011);
INSERT INTO stops (name, section, remote_id) VALUES ('19 Av E & E Galer St', '1', 1614);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av & Broad St', '2', 3526);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av & Columbia St', '2', 213);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av & Lenora St', '2', 220);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av & Lenora St Sb', '2', 221);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av & Madison St', '2', 206);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av & Marion', '2', 208);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av & Pike St', '2', 216);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av & Pine St', '2', 217);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av & Seneca St', '2', 211);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av & University St', '2', 207);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av & Virginia St', '2', 219);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av Ext S & S Jackson St', '2', 201);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av Ext S & S Washington St', '2', 203);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av S & S Jackson St', '2', 227);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av S & S King St', '2', 4028);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av S & S Main St', '2', 228);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av S & S Washington St', '2', 229);
INSERT INTO stops (name, section, remote_id) VALUES ('2 Av W & W Roy St', '2', 4370);
INSERT INTO stops (name, section, remote_id) VALUES ('21 Av & E James St', '2', 2131);
INSERT INTO stops (name, section, remote_id) VALUES ('22 Av W & Gilman Av W', '2', 3553);
INSERT INTO stops (name, section, remote_id) VALUES ('23 Av & E Jefferson St', '2', 3908);
INSERT INTO stops (name, section, remote_id) VALUES ('23 Av & E Union St', '2', 3904);
INSERT INTO stops (name, section, remote_id) VALUES ('23 Av & E Yesler Wy', '2', 3916);
INSERT INTO stops (name, section, remote_id) VALUES ('23 Av E & E Aloha St', '2', 3924);
INSERT INTO stops (name, section, remote_id) VALUES ('23 Av E & E John St', '2', 3927);
INSERT INTO stops (name, section, remote_id) VALUES ('23 Av E & E Madison St', '2', 3917);
INSERT INTO stops (name, section, remote_id) VALUES ('23 Av S & S Jackson St', '2', 3922);
INSERT INTO stops (name, section, remote_id) VALUES ('24 Av E & Boyer Ave E', '2', 3929);
INSERT INTO stops (name, section, remote_id) VALUES ('24 Av NW & NW 65 St', '2', 3012);
INSERT INTO stops (name, section, remote_id) VALUES ('24 Av NW & NW Market St', '2', 3042);
INSERT INTO stops (name, section, remote_id) VALUES ('25 Av NE & NE 75 St', '2', 5598);
INSERT INTO stops (name, section, remote_id) VALUES ('25 Av S & S Walker St', '2', 4737);
INSERT INTO stops (name, section, remote_id) VALUES ('26 Av SW & SW Spokane St (E/B)', '2', 701);
INSERT INTO stops (name, section, remote_id) VALUES ('26 Av SW & SW Spokane St (W/B)', '2', 816);
INSERT INTO stops (name, section, remote_id) VALUES ('28 Av NW & NW Market St', '2', 3085);
INSERT INTO stops (name, section, remote_id) VALUES ('28 Av W & W Blaine St', '2', 3510);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av & Bell St', '3', 322);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av & Cedar St', '3', 326);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av & Cherry St', '3', 309);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av & James St', '3', 306);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av & Marion St', '3', 308);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av & Pike St', '3', 316);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av & Pine St', '3', 317);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av & Seneca St', '3', 311);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av & Union St', '3', 314);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av & Virginia St', '3', 319);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av & Yesler Wy', '3', 304);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av S & S Jackson St', '3', 301);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av S & S Main St', '3', 302);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av S & S Washington St', '3', 303);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av W & W Cremona St', '3', 4356);
INSERT INTO stops (name, section, remote_id) VALUES ('3 Av W & W Nickerson St', '3', 4308);
INSERT INTO stops (name, section, remote_id) VALUES ('31 Av S & Yesler Wy', '3', 3977);
INSERT INTO stops (name, section, remote_id) VALUES ('31 Av W & W McGraw St', '3', 3546);
INSERT INTO stops (name, section, remote_id) VALUES ('32 Av & E Cherry St', '3', 3959);
INSERT INTO stops (name, section, remote_id) VALUES ('32 Av NW & NW 54 St', '3', 3014);
INSERT INTO stops (name, section, remote_id) VALUES ('33 Av & E Union St', '3', 3920);
INSERT INTO stops (name, section, remote_id) VALUES ('34 Av & E Union St', '3', 3903);
INSERT INTO stops (name, section, remote_id) VALUES ('34 Av W & W Government Wy', '3', 3508);
INSERT INTO stops (name, section, remote_id) VALUES ('34 Av W & W McGraw St', '3', 3509);
INSERT INTO stops (name, section, remote_id) VALUES ('34 Av W & W Smith St', '3', 3514);
INSERT INTO stops (name, section, remote_id) VALUES ('35 Av NE & NE 55 St', '3', 5518);
INSERT INTO stops (name, section, remote_id) VALUES ('35 Av NE & NE 65 St', '3', 5519);
INSERT INTO stops (name, section, remote_id) VALUES ('35 Av SW & SW Avalon Wy', '3', 722);
INSERT INTO stops (name, section, remote_id) VALUES ('35 Av SW & SW Oregon St', '3', 6054);
INSERT INTO stops (name, section, remote_id) VALUES ('35 Av W & W McGraw St', '3', 3516);
INSERT INTO stops (name, section, remote_id) VALUES ('36 Av S & S Atlantic St', '3', 3915);
INSERT INTO stops (name, section, remote_id) VALUES ('36 Av S & S Oregon St', '3', 4709);
INSERT INTO stops (name, section, remote_id) VALUES ('37 Av SW & SW Alaska St(Farside)', '3', 6055);
INSERT INTO stops (name, section, remote_id) VALUES ('38 Av S & S Genesee St', '3', 4730);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av & Battery St', '4', 423);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av & Bell St', '4', 422);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av & James St', '4', 406);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av & Lenora St', '4', 420);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av & Pike St', '4', 416);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av & Seneca St', '4', 411);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av & Spring St', '4', 410);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av & Stewart St', '4', 418);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av & Union St', '4', 414);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av & University St', '4', 413);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av & Virginia St', '4', 419);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av N & Mercer St', '4', 4364);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av N & Roy St', '4', 4363);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av S & S Holgate St', '4', 4059);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av S & S Jackson St', '4', 401);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av S & S Lander St', '4', 4035);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av S & S Royal Brougham Wy', '4', 4020);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av S & S Spokane St (N/B)', '4', 4010);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av S & S Spokane St (S/B)', '4', 4052);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av S & S Washington St', '4', 403);
INSERT INTO stops (name, section, remote_id) VALUES ('4 Av S Island & S Jackson St', '4', 402);
INSERT INTO stops (name, section, remote_id) VALUES ('40 Av NE & NE 75 St', '4', 5560);
INSERT INTO stops (name, section, remote_id) VALUES ('42 Av E & E McGilvra St', '4', 3912);
INSERT INTO stops (name, section, remote_id) VALUES ('42 Av NE & NE 45 St', '4', 5932);
INSERT INTO stops (name, section, remote_id) VALUES ('47 Av NE & NE 45 St', '4', 5941);
INSERT INTO stops (name, section, remote_id) VALUES ('49 Av SW & SW Hanford', '4', 6045);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av & Blanchard St', '5', 521);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av & Cherry St', '5', 507);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av & Lenora St', '5', 520);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av & Olive Wy', '5', 543);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av & Pike St', '5', 516);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av & Pine St', '5', 517);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av & Terrace St', '5', 505);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av & Wall St', '5', 524);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av N & Broad St', '5', 4355);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av N & Mercer St', '5', 4301);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av N & Republican St', '5', 4319);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av NE & NE 45 St', '5', 1131);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av NE & NE 50 St', '5', 5644);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av S & S Dearborn St', '5', 2518);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av S & S Jackson St', '5', 501);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av S & S Main St', '5', 502);
INSERT INTO stops (name, section, remote_id) VALUES ('5 Av S & S Washington St', '5', 503);
INSERT INTO stops (name, section, remote_id) VALUES ('50 Av NE & NE 75 St', '5', 5629);
INSERT INTO stops (name, section, remote_id) VALUES ('50 Av Nene 41 St', '5', 5684);
INSERT INTO stops (name, section, remote_id) VALUES ('54 Av NE & E Laurel Dr NE', '5', 5921);
INSERT INTO stops (name, section, remote_id) VALUES ('55 Av NE & NE 65 St', '5', 5647);
INSERT INTO stops (name, section, remote_id) VALUES ('55 Av SW & SW Dakota St', '5', 6007);
INSERT INTO stops (name, section, remote_id) VALUES ('6 Av & Battery St', '6', 623);
INSERT INTO stops (name, section, remote_id) VALUES ('6 Av & Blanchard St', '6', 621);
INSERT INTO stops (name, section, remote_id) VALUES ('6 Av & Lenora St', '6', 620);
INSERT INTO stops (name, section, remote_id) VALUES ('6 Av & Pike St', '6', 616);
INSERT INTO stops (name, section, remote_id) VALUES ('6 Av & Pine St', '6', 617);
INSERT INTO stops (name, section, remote_id) VALUES ('6 Av & Union St', '6', 615);
INSERT INTO stops (name, section, remote_id) VALUES ('6 Av & Wall St', '6', 624);
INSERT INTO stops (name, section, remote_id) VALUES ('6 Av S & S Atlantic St', '6', 4038);
INSERT INTO stops (name, section, remote_id) VALUES ('6 Av S & S Atlantic St Lay', '6', 4045);
INSERT INTO stops (name, section, remote_id) VALUES ('6 Av S & S Massachusetts St', '6', 4828);
INSERT INTO stops (name, section, remote_id) VALUES ('6 Av S & S Royal Brougham Wy', '6', 2507);
INSERT INTO stops (name, section, remote_id) VALUES ('61 Av SW & Alki Av SW', '6', 6017);
INSERT INTO stops (name, section, remote_id) VALUES ('63 Av NE & NE 74 St', '6', 5714);
INSERT INTO stops (name, section, remote_id) VALUES ('63 Av SW & Alki Av SW', '6', 6056);
INSERT INTO stops (name, section, remote_id) VALUES ('7 Av & Bell St', '7', 1636);
INSERT INTO stops (name, section, remote_id) VALUES ('7 Av & Blanchard St', '7', 1647);
INSERT INTO stops (name, section, remote_id) VALUES ('7 Av & Lenora', '7', 1638);
INSERT INTO stops (name, section, remote_id) VALUES ('7 Av & Olive Wy', '7', 1634);
INSERT INTO stops (name, section, remote_id) VALUES ('7 Av NE & NE 42 St', '7', 5907);
INSERT INTO stops (name, section, remote_id) VALUES ('7 Av NE & NE 45 St', '7', 5930);
INSERT INTO stops (name, section, remote_id) VALUES ('7 Av NE & NE 47 St', '7', 5615);
INSERT INTO stops (name, section, remote_id) VALUES ('7 Av W & W Raye St', '7', 4323);
INSERT INTO stops (name, section, remote_id) VALUES ('8 Av & Bell St Layover Farside', '8', 822);
INSERT INTO stops (name, section, remote_id) VALUES ('8 Av & Blanchard St', '8', 1655);
INSERT INTO stops (name, section, remote_id) VALUES ('8 Av & Blanchard St Eastbound', '8', 1649);
INSERT INTO stops (name, section, remote_id) VALUES ('8 Av & Olive Wy', '8', 1629);
INSERT INTO stops (name, section, remote_id) VALUES ('8 Av & Westlake Av', '8', 1684);
INSERT INTO stops (name, section, remote_id) VALUES ('8 Av NW & NW 65 St', '8', 3049);
INSERT INTO stops (name, section, remote_id) VALUES ('8 Av NW & NW Market St', '8', 3021);
INSERT INTO stops (name, section, remote_id) VALUES ('8 Av S & S King St', '8', 2642);
INSERT INTO stops (name, section, remote_id) VALUES ('9 Av & Howell St', '9', 1628);
INSERT INTO stops (name, section, remote_id) VALUES ('9 Av & Jefferson St', '9', 2123);
INSERT INTO stops (name, section, remote_id) VALUES ('9 Av & Olive Wy (Eastbnd)', '9', 1666);
INSERT INTO stops (name, section, remote_id) VALUES ('9 Av & Pine St', '9', 1660);
INSERT INTO stops (name, section, remote_id) VALUES ('9 Av & Pine St (S/B)', '9', 1682);
INSERT INTO stops (name, section, remote_id) VALUES ('9 Av & Seneca St', '9', 2128);
INSERT INTO stops (name, section, remote_id) VALUES ('9 Av & Spring St', '9', 2163);
INSERT INTO stops (name, section, remote_id) VALUES ('9 Av & Stewart St', '9', 1623);
INSERT INTO stops (name, section, remote_id) VALUES ('9 Av N & Mercer St', '9', 4316);
INSERT INTO stops (name, section, remote_id) VALUES ('9 Av NE & NE 45 St', '9', 5677);
INSERT INTO stops (name, section, remote_id) VALUES ('Airport Wy S &  S Industrial Wy', 'A', 2681);
INSERT INTO stops (name, section, remote_id) VALUES ('Alaska Junction Bay 1', 'A', 710);
INSERT INTO stops (name, section, remote_id) VALUES ('Alaska Junction Bay 2', 'A', 711);
INSERT INTO stops (name, section, remote_id) VALUES ('Alaska Junction Bay 3', 'A', 709);
INSERT INTO stops (name, section, remote_id) VALUES ('Alaska Junction Bay 4', 'A', 708);
INSERT INTO stops (name, section, remote_id) VALUES ('Alaska Junction Bay 5', 'A', 6022);
INSERT INTO stops (name, section, remote_id) VALUES ('Alaska Junction Bay 6', 'A', 712);
INSERT INTO stops (name, section, remote_id) VALUES ('Alaskan Wy & Clay St', 'A', 4061);
INSERT INTO stops (name, section, remote_id) VALUES ('Alaskan Wy S & S Main St', 'A', 4018);
INSERT INTO stops (name, section, remote_id) VALUES ('Atlantic Base NW Yard', 'A', 2520);
INSERT INTO stops (name, section, remote_id) VALUES ('Aurora Av & Denny Wy', 'A', 4366);
INSERT INTO stops (name, section, remote_id) VALUES ('Aurora Av N & N 46 St (N/B)', 'A', 1143);
INSERT INTO stops (name, section, remote_id) VALUES ('Aurora Av N & N 46 St (S/B)', 'A', 1144);
INSERT INTO stops (name, section, remote_id) VALUES ('Ballard Av NW & NW Market St', 'B', 3013);
INSERT INTO stops (name, section, remote_id) VALUES ('Beacon Av S & S Lander St', 'B', 2595);
INSERT INTO stops (name, section, remote_id) VALUES ('Beacon Av S & S Spokane St', 'B', 2510);
INSERT INTO stops (name, section, remote_id) VALUES ('Bellevue Av  & E Pike St', 'B', 2109);
INSERT INTO stops (name, section, remote_id) VALUES ('Bellevue Av & E Olive St', 'B', 1632);
INSERT INTO stops (name, section, remote_id) VALUES ('Bellevue Av E & Bellevue Pl E', 'B', 1619);
INSERT INTO stops (name, section, remote_id) VALUES ('Boren Av & E Yesler Wy', 'B', 2170);
INSERT INTO stops (name, section, remote_id) VALUES ('Boren Av & Madison St', 'B', 2113);
INSERT INTO stops (name, section, remote_id) VALUES ('Boylston Av E & E Roanoke St', 'B', 5927);
INSERT INTO stops (name, section, remote_id) VALUES ('Bridge Wy N & N 38 St', 'B', 1135);
INSERT INTO stops (name, section, remote_id) VALUES ('Broadway & E Jefferson St', 'B', 2125);
INSERT INTO stops (name, section, remote_id) VALUES ('Broadway & E Madison St', 'B', 2153);
INSERT INTO stops (name, section, remote_id) VALUES ('Broadway & E Pine St', 'B', 1608);
INSERT INTO stops (name, section, remote_id) VALUES ('Broadway & E Union St', 'B', 2121);
INSERT INTO stops (name, section, remote_id) VALUES ('Broadway & Yesler Wy', 'B', 2144);
INSERT INTO stops (name, section, remote_id) VALUES ('Broadway E & E John St', 'B', 1627);
INSERT INTO stops (name, section, remote_id) VALUES ('Broadway E & E Roy St', 'B', 1658);
INSERT INTO stops (name, section, remote_id) VALUES ('Brooklyn Av NE & NE 50 St', 'B', 5524);
INSERT INTO stops (name, section, remote_id) VALUES ('Brooklyn Av NE & NE Boat St', 'B', 5681);
INSERT INTO stops (name, section, remote_id) VALUES ('Brooklyn Av NE & NE Campus Pkwy (E/B)', 'B', 5918);
INSERT INTO stops (name, section, remote_id) VALUES ('Brooklyn Av NE & NE Campus Pkwy (Nb)', 'B', 5952);
INSERT INTO stops (name, section, remote_id) VALUES ('California Av SW & SW Admiral Wy', 'C', 6003);
INSERT INTO stops (name, section, remote_id) VALUES ('California Av SW & SW Atlantic St', 'C', 6014);
INSERT INTO stops (name, section, remote_id) VALUES ('California Av SW & SW Lander St', 'C', 6004);
INSERT INTO stops (name, section, remote_id) VALUES ('California Av SW & SW Oregon St', 'C', 6039);
INSERT INTO stops (name, section, remote_id) VALUES ('Center Park', 'C', 3986);
INSERT INTO stops (name, section, remote_id) VALUES ('Chelan Av SW & SW Spokane St', 'C', 704);
INSERT INTO stops (name, section, remote_id) VALUES ('Childrens Hospital & Medical Center', 'C', 5908);
INSERT INTO stops (name, section, remote_id) VALUES ('Claremont Av S & S Walden St', 'C', 2539);
INSERT INTO stops (name, section, remote_id) VALUES ('Conv Pl N/B Sta To Reg. I-5 Lanes', 'C', 1748);
INSERT INTO stops (name, section, remote_id) VALUES ('Convention Pl Stn Bay E', 'C', 1753);
INSERT INTO stops (name, section, remote_id) VALUES ('Convention Pl Stn N/B Bay A/B', 'C', 1749);
INSERT INTO stops (name, section, remote_id) VALUES ('Convention Place S/B Bay C', 'C', 1751);
INSERT INTO stops (name, section, remote_id) VALUES ('Convention Place S/B Bay D', 'C', 1752);
INSERT INTO stops (name, section, remote_id) VALUES ('Convention Place Station (All Bays)', 'C', 10016);
INSERT INTO stops (name, section, remote_id) VALUES ('Convention Place Station Southbound', 'C', 1750);
INSERT INTO stops (name, section, remote_id) VALUES ('Corwin Pl S & S Dearborn St', 'C', 2522);
INSERT INTO stops (name, section, remote_id) VALUES ('Denny Wy & Warren Pl', 'D', 4300);
INSERT INTO stops (name, section, remote_id) VALUES ('Dexter Av N & Republican St', 'D', 4318);
INSERT INTO stops (name, section, remote_id) VALUES ('Dexter Av Ndenny Wy', 'D', 1664);
INSERT INTO stops (name, section, remote_id) VALUES ('E Green Lake Wy N & NE Ravenna Blvd', 'E', 1225);
INSERT INTO stops (name, section, remote_id) VALUES ('Eastlake Av E & 1000 Block', 'E', 1665);
INSERT INTO stops (name, section, remote_id) VALUES ('Eastlake Av E & E Nelson Pl', 'E', 1641);
INSERT INTO stops (name, section, remote_id) VALUES ('Eastlake Av E & Harvard Av E', 'E', 5906);
INSERT INTO stops (name, section, remote_id) VALUES ('Elliott Av W & W Lee St', 'E', 4112);
INSERT INTO stops (name, section, remote_id) VALUES ('Fairview Av N & Denny Wy', 'F', 1663);
INSERT INTO stops (name, section, remote_id) VALUES ('Fairview Av N & Ward St', 'F', 1688);
INSERT INTO stops (name, section, remote_id) VALUES ('Fairview Av N & Yale St', 'F', 1689);
INSERT INTO stops (name, section, remote_id) VALUES ('Fauntleroy Wy SW & SW Oregon St', 'F', 6050);
INSERT INTO stops (name, section, remote_id) VALUES ('Fremont Av N & N 34 St', 'F', 1124);
INSERT INTO stops (name, section, remote_id) VALUES ('Fremont Pl N & N 35 St', 'F', 1140);
INSERT INTO stops (name, section, remote_id) VALUES ('Fremont Wy N & N 38 St', 'F', 1137);
INSERT INTO stops (name, section, remote_id) VALUES ('Fuhrman Av E & Franklin Av E', 'F', 5924);
INSERT INTO stops (name, section, remote_id) VALUES ('Gilman Av W & W Emerson Pl', 'G', 3545);
INSERT INTO stops (name, section, remote_id) VALUES ('Grant Ln & G Washington Ln', 'G', 5954);
INSERT INTO stops (name, section, remote_id) VALUES ('Green Lake P & R', 'G', 1213);
INSERT INTO stops (name, section, remote_id) VALUES ('Harbor Av SW & SW Spokane St', 'H', 6026);
INSERT INTO stops (name, section, remote_id) VALUES ('Harvard Av E & E Roanoke St', 'H', 5914);
INSERT INTO stops (name, section, remote_id) VALUES ('Hubbell Pl & Seneca St', 'H', 2130);
INSERT INTO stops (name, section, remote_id) VALUES ('I 5 & NE 45 St', 'I', 5919);
INSERT INTO stops (name, section, remote_id) VALUES ('I 90 & Rainier Av S Freeway Station', 'I', 4824);
INSERT INTO stops (name, section, remote_id) VALUES ('I-5/NE Ravenna Blvd S/B', 'I', 5680);
INSERT INTO stops (name, section, remote_id) VALUES ('I-90 Fwy Station Exp Lns', 'I', 4826);
INSERT INTO stops (name, section, remote_id) VALUES ('Illinois Av & Texas Wy', 'I', 3519);
INSERT INTO stops (name, section, remote_id) VALUES ('International District N/B Bay A', 'I', 451);
INSERT INTO stops (name, section, remote_id) VALUES ('International District N/B Bay B', 'I', 452);
INSERT INTO stops (name, section, remote_id) VALUES ('International District Sta Northbound', 'I', 449);
INSERT INTO stops (name, section, remote_id) VALUES ('International District Sta Southbound', 'I', 450);
INSERT INTO stops (name, section, remote_id) VALUES ('International District Station (All Directions)', 'I', 10014);
INSERT INTO stops (name, section, remote_id) VALUES ('Lake City Wy & I-5 Sb Exp Lanes', 'L', 3684);
INSERT INTO stops (name, section, remote_id) VALUES ('Lake City Wy & I-5 Sb Reg Lanes', 'L', 3685);
INSERT INTO stops (name, section, remote_id) VALUES ('Lake Wash Blvd & Madrona Dr', 'L', 3913);
INSERT INTO stops (name, section, remote_id) VALUES ('Latona Av NE & NE 40 St', 'L', 1128);
INSERT INTO stops (name, section, remote_id) VALUES ('Latona Av NE & NE 45 St', 'L', 1132);
INSERT INTO stops (name, section, remote_id) VALUES ('Leary Av NW & NW Vernon Pl', 'L', 3017);
INSERT INTO stops (name, section, remote_id) VALUES ('Lenora St & Westlake Av', 'L', 1690);
INSERT INTO stops (name, section, remote_id) VALUES ('M. L. King Jr Wy E & E Madison St', 'M', 3907);
INSERT INTO stops (name, section, remote_id) VALUES ('M. L. King Jr Wy S & S Hanford St', 'M', 2529);
INSERT INTO stops (name, section, remote_id) VALUES ('M. L. King Jr Wy S & S Massachusetts St', 'M', 2651);
INSERT INTO stops (name, section, remote_id) VALUES ('M. L. King Jr Wy S & S McClellan St', 'M', 4786);
INSERT INTO stops (name, section, remote_id) VALUES ('Magnolia Blvd W & W Emerson St', 'M', 3522);
INSERT INTO stops (name, section, remote_id) VALUES ('Mary Gates Memorial Drive NE & NE 45 St', 'M', 5933);
INSERT INTO stops (name, section, remote_id) VALUES ('McGilvra Blvd E & E Madison St', 'M', 3985);
INSERT INTO stops (name, section, remote_id) VALUES ('Memorial Wy & G. Washington Lane', 'M', 5940);
INSERT INTO stops (name, section, remote_id) VALUES ('Memorial Wy & Stevens Wy', 'M', 5920);
INSERT INTO stops (name, section, remote_id) VALUES ('Minor Av & Stewart St', 'M', 1685);
INSERT INTO stops (name, section, remote_id) VALUES ('Montlake Blvd E & E Shelby St', 'M', 3919);
INSERT INTO stops (name, section, remote_id) VALUES ('Montlake Blvd NE & NE Pacific Pl', 'M', 5916);
INSERT INTO stops (name, section, remote_id) VALUES ('Montlake Freeway Station (All Directions)', 'M', 10018);
INSERT INTO stops (name, section, remote_id) VALUES ('Montlake Freeway Station (E/B)', 'M', 3898);
INSERT INTO stops (name, section, remote_id) VALUES ('Montlake Freeway Station (NS/B)', 'M', 3926);
INSERT INTO stops (name, section, remote_id) VALUES ('Montlake Freeway Station (W/B)', 'M', 3899);
INSERT INTO stops (name, section, remote_id) VALUES ('Mt Rainier Dr S & Mt St Helens Pl S', 'M', 4713);
INSERT INTO stops (name, section, remote_id) VALUES ('N 46 St & Green Lake Way N', 'N', 129557);
INSERT INTO stops (name, section, remote_id) VALUES ('NE Pacific Pl & NE Pacific St', 'N', 5925);
INSERT INTO stops (name, section, remote_id) VALUES ('NE Ravenna Blvd & NE 70 St', 'N', 1231);
INSERT INTO stops (name, section, remote_id) VALUES ('Nb Sand Point Wy NE & NE 50 St', 'N', 5980);
INSERT INTO stops (name, section, remote_id) VALUES ('Newport Wy & Madrona Dr', 'N', 3936);
INSERT INTO stops (name, section, remote_id) VALUES ('Noaa Building 3 (Sandpoint)', 'N', 5635);
INSERT INTO stops (name, section, remote_id) VALUES ('Nob Hill Av N & Galer St', 'N', 4305);
INSERT INTO stops (name, section, remote_id) VALUES ('Olive Way & I-5 Regular Lanes', 'O', 2175);
INSERT INTO stops (name, section, remote_id) VALUES ('Phinney Av N & N 46 St', 'P', 1121);
INSERT INTO stops (name, section, remote_id) VALUES ('Phinney Av N & N 65 St', 'P', 1129);
INSERT INTO stops (name, section, remote_id) VALUES ('Pier 55', 'P', 6075);
INSERT INTO stops (name, section, remote_id) VALUES ('Pike St & I-5 Express Lanes', 'P', 2176);
INSERT INTO stops (name, section, remote_id) VALUES ('Queen Anne Av N & Boston St', 'Q', 4302);
INSERT INTO stops (name, section, remote_id) VALUES ('Queen Anne Av N & Galer St', 'Q', 4307);
INSERT INTO stops (name, section, remote_id) VALUES ('Queen Anne Av N & McGraw St', 'Q', 4317);
INSERT INTO stops (name, section, remote_id) VALUES ('Queen Anne Av N & Mercer St', 'Q', 4313);
INSERT INTO stops (name, section, remote_id) VALUES ('Queen Anne Av N & Roy St', 'Q', 4310);
INSERT INTO stops (name, section, remote_id) VALUES ('Rainier Av S & S Genesee St', 'R', 4714);
INSERT INTO stops (name, section, remote_id) VALUES ('Rainier Av S & S McClellan St', 'R', 4722);
INSERT INTO stops (name, section, remote_id) VALUES ('Rainier Av S & S Oregon St', 'R', 4711);
INSERT INTO stops (name, section, remote_id) VALUES ('Rainier Av S & S Walker St', 'R', 4717);
INSERT INTO stops (name, section, remote_id) VALUES ('Roosevelt Wy NE & NE 45 St', 'R', 5910);
INSERT INTO stops (name, section, remote_id) VALUES ('Roosevelt Wy NE & NE 75 St', 'R', 5531);
INSERT INTO stops (name, section, remote_id) VALUES ('Sand Point Wy NE & NE 74 St', 'S', 5514);
INSERT INTO stops (name, section, remote_id) VALUES ('Sb Sand Point Wy NE & NE 50 St', 'S', 5981);
INSERT INTO stops (name, section, remote_id) VALUES ('Seacrest Dock', 'S', 6074);
INSERT INTO stops (name, section, remote_id) VALUES ('Seacrest Marina Parking Lot', 'S', 6071);
INSERT INTO stops (name, section, remote_id) VALUES ('Seattle Ferry Terminal', 'S', 4001);
INSERT INTO stops (name, section, remote_id) VALUES ('Sodo Busway & S Holgate St', 'S', 4058);
INSERT INTO stops (name, section, remote_id) VALUES ('Sodo Busway & S Lander St', 'S', 4060);
INSERT INTO stops (name, section, remote_id) VALUES ('Sodo Busway & S Royal Brougham Wy', 'S', 4047);
INSERT INTO stops (name, section, remote_id) VALUES ('Sodo Busway & S Spokane St', 'S', 4046);
INSERT INTO stops (name, section, remote_id) VALUES ('South Lake Union Streetcar Barn', 'S', 14);
INSERT INTO stops (name, section, remote_id) VALUES ('Stone Wy N & N 34 St', 'S', 1105);
INSERT INTO stops (name, section, remote_id) VALUES ('Stone Wy N & N 40 St', 'S', 1123);
INSERT INTO stops (name, section, remote_id) VALUES ('Stone Wy N & N 45 St', 'S', 1102);
INSERT INTO stops (name, section, remote_id) VALUES ('Terry Av & Seneca St', 'T', 2162);
INSERT INTO stops (name, section, remote_id) VALUES ('Terry Av & Spruce St', 'T', 2135);
INSERT INTO stops (name, section, remote_id) VALUES ('Terry Av N & Harrison St', 'T', 1686);
INSERT INTO stops (name, section, remote_id) VALUES ('Thackeray Pl NE & NE 45 St', 'T', 1133);
INSERT INTO stops (name, section, remote_id) VALUES ('Thorndyke Av W & W Blaine St', 'T', 3517);
INSERT INTO stops (name, section, remote_id) VALUES ('U Wy NE & NE Pac St Sb', 'U', 5683);
INSERT INTO stops (name, section, remote_id) VALUES ('UW Campus Hub', 'U', 5903);
INSERT INTO stops (name, section, remote_id) VALUES ('Univ Wy NE & NE Pacific St Nb', 'U', 5542);
INSERT INTO stops (name, section, remote_id) VALUES ('University District Transfer Point', 'U', 10019);
INSERT INTO stops (name, section, remote_id) VALUES ('University Street Station (All Directions)', 'U', 10015);
INSERT INTO stops (name, section, remote_id) VALUES ('University Street Station Northbound', 'U', 336);
INSERT INTO stops (name, section, remote_id) VALUES ('University Street Station Southbound', 'U', 332);
INSERT INTO stops (name, section, remote_id) VALUES ('University Wy NE & NE 45 St', 'U', 5923);
INSERT INTO stops (name, section, remote_id) VALUES ('University Wy NE & NE Campus Pkwy', 'U', 5942);
INSERT INTO stops (name, section, remote_id) VALUES ('Veterans Administration Hospital', 'V', 2614);
INSERT INTO stops (name, section, remote_id) VALUES ('Westlake Av & Stewart St', 'W', 1656);
INSERT INTO stops (name, section, remote_id) VALUES ('Westlake Av & Virginia St', 'W', 1637);
INSERT INTO stops (name, section, remote_id) VALUES ('Westlake Av N & Harrison St', 'W', 1687);
INSERT INTO stops (name, section, remote_id) VALUES ('Westlake Av N & Mercer St', 'W', 1617);
INSERT INTO stops (name, section, remote_id) VALUES ('Westlake Streetcar Station', 'W', 1691);
INSERT INTO stops (name, section, remote_id) VALUES ('Woodlawn Av NE & NE Ravenna Blvd', 'W', 1118);
INSERT INTO stops (name, section, remote_id) VALUES ('Yale Av & Stewart St', 'Y', 1612);
INSERT INTO stops (name, section, remote_id) VALUES ('Yesler Wy & Post Av', 'Y', 4041);
